### ISSUE TITLE
Install from repo. Missing dependencies.

### ISSUE THREAD

**Issue by robons17** [awawa-dev/awawa-dev.github.io#1]
Hello,
today i'm trying to install 19.0.0 beta2 from repo on fresh raspian lite os.
HyperHDR does not start for missing libraries (X not install in lite OS)
Installing all the needed libraries manually fix.
I'm sorry but i don't have any log.

**Comment by awawa-dev** [comment]
Which version of Raspberry Pi OS: armv6 or aarch64? Do you have a direct download link to OS image?

**Comment by robons17** [comment]
I use Raspberry Pi Imager and write 64bit lite version.

**Comment by awawa-dev** [comment]
I tested it and I do not confirm such a problem exists at all.
This version of OS was installed.
![obraz](https://user-images.githubusercontent.com/69086569/215287875-cb901531-09b5-495c-bc61-6104f53553f7.png)
Later I installed HyperHDR from the repo following manual from here:
https://github.com/awawa-dev/awawa-dev.github.io
and it works without a need to install any additional libraries/packages.

**Comment by robons17** [comment]
I do exacttly the same last time. I retry it next week and i share with you.

**Comment by awawa-dev** [comment]
OK, but this `"HyperHDR does not start for missing libraries (X not install in lite OS)"`
HyperHDR is not dependent on whether the system is running X or not. It can run perfectly fine as a daemon (I run it this way on daily basis and SD images from HyperHDR also are based on Raspbian OS lite version) and its default action. Unless you were trying to do some unusual action (which is not supported, use HyperHDR SD images to have a support).

**Comment by robons17** [comment]
I write about x server because for example i have to install libqt. The
only thing i have done different Is that before installing hyperhdr i
upgrade system.
So:
Fresh install raspian os 64 bit lite
Upgrade system
Add repo
Install hyperhdr



Il dom 29 gen 2023, 22:47 Awawa ***@***.***> ha scritto:

**Comment by awawa-dev** [comment]
Add which command did you use to upgrade the system? There are already included update&upgrade commands in the manual and it works

**Comment by robons17** [comment]
I review manuale and i see only update command not upgrade. Am i missing
something?
Before add repo and install i do APT update and APT upgrade. So all
libraries was updated before installing. I LL do some screen when retry on
fresh installation.

Il lun 30 gen 2023, 07:16 Awawa ***@***.***> ha scritto:

**Comment by awawa-dev** [comment]
Yes, upgrade is only for HyperHDR in manual and update for all components. I'll check later if apt upgrade breaks the test system.

**Comment by robons17** [comment]
I do It before add repo and install

Il lun 30 gen 2023, 14:03 Awawa ***@***.***> ha scritto:

**Comment by awawa-dev** [comment]
It doesnt matter: missing library is still a missing library. Just a moment..

**Comment by awawa-dev** [comment]
Nope, it's still working fine after apt update&upgrade.

EOT
